# Project information
site_name: MY-Injection-Molding
site_url: "https://my-machines.net/MY-Injection-Molding/"
site_author: "Edgar Mata"
site_description: "My Machines Knowledge Center"

# Repository
repo_name: "MY-Injection-Molding"
repo_url: "https://github.com/EdgarMata/MY-Injection-Molding"

# Copyright
# copyright: '&copy; 2025 <a href="https://my-machines.net/" target="_blank" rel="noopener">My Machines</a> by Edgar Mata'
copyright: '&copy; 2022 - <span id="current-year"></span> <a href="https://my-machines.net/" target="_blank" rel="noopener">My Machines</a> by Edgar Mata'


# Configuration
theme:
  name: material
  language: 'en'
  logo: assets/mylogo.svg
  favicon: images/favicon.png
  custom_dir: overrides  
  features:
    - navigation.tabs
#   - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - navigation.path
    - navigation.expand
    - navigation.footer 
    - toc.follow  
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - header.autohide       


  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: System preferences

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light blue
      accent: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: light blue
      accent: indigo

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16  

plugins:
  - search  # O plugin de pesquisa que já deve ter
# - git-revision-date-localized:
#     enable_creation_date: true
#     enable_git_follow: false    

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/EdgarMata
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/machines.net/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/machines_net/
    - icon: fontawesome/brands/pinterest
      link: https://pt.pinterest.com/machines_net
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@machines_net
    - icon: fontawesome/solid/paper-plane
      link: mailto:geral@my-machines.net
  analytics:
    provider: google
    property: G-B2Y6R89EJ9
    feedback:
      title: Did this page help?
      ratings:
        - icon: material/thumb-up-outline
          name: This page helped
          data: 1
          note: >-
            Thank you for your feedback!
        - icon: material/thumb-down-outline
          name: This page can be improved
          data: 0
          note: >- 
            Thank you for your feedback! Help us improve this page
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSf_kuzfD_Tbez4b-jqxr0dPAsu4QGP72imTuG0AKUAi-gQKLg/viewform?usp=pp_url&entry.756152555={url}" target="_blank" rel="noopener">feedback form</a>.     

# announce: |
#  **This page is under constrrrruction.** Please be patient!

extra_css:
#  - assets/custom.css
#  - images/hero.css
- https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
- assets/extra.css

# ... outras configurações ...
extra_javascript:
  - assets/javascripts/extra.js

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - toc:
      permalink: true
      title: Table of Contents
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md

  - Manual:
    - manual/index.md
    - Introduction:
      - Welcome & Safety: manual/introduction/index.md
      - Printing Guidelines: manual/introduction/printing-guidelines.md
      - File Naming Convention: manual/introduction/file-naming.md
      - Hardware Reference: manual/introduction/hardware-reference.md
      - Required Tools: manual/introduction/required-tools.md
      - Core Assembly Techniques: manual/introduction/assembly-techniques.md
    - Assembly Guide:
      - Step 01 Frame: manual/assembly/01-frame.md
      - Step 02 Z-Drives and Idlers: manual/assembly/02-z-drives-and-idlers.md
      - Step 03 Build Plate: manual/assembly/03-build-plate.md
      - Step 04 A/B Drives and Idlers: manual/assembly/04-ab-drives-and-idlers.md
      - Step 05 Gantry: manual/assembly/05-gantry.md
      - Step 06 Z-Axis Installation: manual/assembly/06-z-axis.md
      - Step 07 A/B Belts: manual/assembly/07-ab-belts.md
      - Step 08 Toolhead (EVA Extruder): manual/assembly/08-toolhead.md
    - Electronics and Wiring:
      - Overview: manual/electronics/index.md
      - Component Mounting: manual/electronics/01-component-mounting.md
      - Controller Board Setup: manual/electronics/02-controller-setup.md
      - Mains and PSU Wiring: manual/electronics/03-mains-wiring.md
      - Low Voltage & Signal Wiring: manual/electronics/04-dc-wiring.md
      - Cable Chain Routing: manual/electronics/05-cable-chains.md
    - Final Assembly:
      - Skirts: manual/final-assembly/01-skirts.md
      - Panels and Doors: manual/final-assembly/02-panels.md
      - Exhaust Filter: manual/final-assembly/03-exhaust-filter.md
      - Spool Holder: manual/final-assembly/04-spool-holder.md
    - Initial Setup:
      - Introduction: manual/initial-setup/index.md
      - Printer Overview: manual/initial-setup/printer-overview.md
      - First Time Setup: manual/initial-setup/first-time-setup.md
      - Klipper Interface Guide: manual/initial-setup/klipper-interface-guide.md
      - Loading/Unloading Filament: manual/initial-setup/loading-unloading-filament.md
      - Glossary of Terms: manual/initial-setup/glossary-of-terms.md
    - First Time Use:
      - First Time Startup: manual/first-time-use/first-time-startup.md
      - Preflight Check: manual/first-time-use/preflight-check.md
      - First Print: manual/first-time-use/first-print.md
    - Bill of Materials:
      - Printed Parts: manual/bom/printed-parts.md
      - Accessories: manual/bom/accessories.md
      - Electronics: manual/bom/electronics.md
      - Enclosure: manual/bom/enclosure.md
      - Extruder: manual/bom/extruder.md
      - Fasteners: manual/bom/fasteners.md
      - Frame: manual/bom/frame.md
      - Gantry: manual/bom/gantry.md
      - Heat Bed: manual/bom/heat_bed.md
      - Skirt: manual/bom/skirt.md
      - Z-Motion: manual/bom/z_motion.md

  - Slicer:
    - slicer/index.md
    - Introduction to Slicing: slicer/introduction-to-slicing.md
    - Basic Slicing Workflow: slicer/basic-slicing-workflow.md
    - Understanding Print Settings: slicer/understanding-print-settings.md
    - PrusaSlicer & SuperSlicer: slicer/prusa_and_super_slicer.md
    - PrusaSlicer:
      - Installation: slicer/prusaslicer/installation.md
      - Configuration: slicer/prusaslicer/configuration.md
    - OrcaSlicer:
      - Installation: slicer/orcaslicer/installation.md
      - Configuration: slicer/orcaslicer/configuration.md

  - Maintenance:
    - maintenance/index.md
    - Preventive Maintenance:
      - Maintenance Schedule: maintenance/preventive-maintenance/maintenance-schedule.md
      - Lubrication: maintenance/preventive-maintenance/lubrication.md
      - Belt Tensioning: maintenance/preventive-maintenance/belt-tensioning.md
      - Cleaning Print Bed: maintenance/preventive-maintenance/cleaning-print-bed.md
      - Cleaning Nozzle: maintenance/preventive-maintenance/cleaning-nozzle.md
      - Cleaning Extruder: maintenance/preventive-maintenance/cleaning-extruder.md
      - Nozzle Replacement: maintenance/preventive-maintenance/nozzle-replacement.md
      - Replacing Consumables: maintenance/preventive-maintenance/replacing-consumables.md
    - Reactive Maintenance:
      - Replacing the Hotend: maintenance/reactive-maintenance/replacing-the-hotend.md
      - Replacing the Nozzle: maintenance/reactive-maintenance/replacing-the-nozzle.md
      - Replacing Heater: maintenance/reactive-maintenance/replacing-heater.md
      - Replacing Thermistor: maintenance/reactive-maintenance/replacing-thermistor.md
      - Replacing Fans: maintenance/reactive-maintenance/replacing-fans.md
      
  - Safety:
    - safety/index.md
    - Electrical Safety: safety/electrical-safety.md
    - Thermal Safety: safety/thermal-safety.md
    - Mechanical Safety: safety/mechanical-safety.md
    - Chemical Safety: safety/chemical-safety.md
    - Post-Processing Safety: safety/post-processing-safety.md
    - Fire Prevention: safety/fire-prevention.md
    - Air Quality & Ventilation: safety/air-quality-and-ventilation.md

  - Troubleshooting:
    - troubleshooting/index.md
    - Print Quality Issues:
      - Ghosting (Ringing): troubleshooting/print-quality-issues/ghosting.md
      - Layer Adhesion Issues: troubleshooting/print-quality-issues/layer-adhesion-issues.md
      - Warping: troubleshooting/print-quality-issues/warping.md
      - Stringing or Oozing: troubleshooting/print-quality-issues/stringing.md
      - Banding: troubleshooting/print-quality-issues/banding.md
      - Bridging Issues: troubleshooting/print-quality-issues/bridging.md
      - Elephant Foot: troubleshooting/print-quality-issues/elephant-foot.md
      - Infill Issues: troubleshooting/print-quality-issues/infill-issues.md
      - Overhang Issues: troubleshooting/print-quality-issues/overhangs.md
      - Pillowing: troubleshooting/print-quality-issues/pillowing.md
    - Extrusion Issues:
      - General Extrusion Problems: troubleshooting/extrusion-issues/extrusion-problems.md
      - Under-Extrusion: troubleshooting/extrusion-issues/under-extrusion.md
      - Over-Extrusion: troubleshooting/extrusion-issues/over-extrusion.md
    - Mechanical & Movement Issues:
      - Layer Shifting: troubleshooting/mechanical-&-movement-issues/layer-shifting.md
      - Skipping Layers: troubleshooting/mechanical-&-movement-issues/layers-skipping.md
      - Z-Axis Issues: troubleshooting/mechanical-&-movement-issues/z-axis-issues.md
      - General Hardware Issues: troubleshooting/mechanical-&-movement-issues/hardware-issues.md
    - System & Connectivity:
      - Software Issues: troubleshooting/system-&-connectivity/software-issues.md
      - Connectivity Issues: troubleshooting/system-&-connectivity/connectivity-issues.md

  - Tips and Tricks:
    - tips-and-tricks/index.md
    - Perfect First Layer: tips-and-tricks/perfect-first-layer.md
    - Better Cooling: tips-and-tricks/better-cooling.md
    - Reduce Vibration: tips-and-tricks/reduce-vibration.md
    - Hardware & Calibration:
      - Fine Tuning First Layer: tips-and-tricks/hardware-&-calibration/fine_tuning_first_layer.md
      - Input Shaping: tips-and-tricks/hardware-&-calibration/input-shaping.md
      - Pressure Advance: tips-and-tricks/hardware-&-calibration/pressure-advance.md
    - Reducing Stringing: tips-and-tricks/reducing-stringing.md
    - Preventing Warping: tips-and-tricks/preventing-warping.md
    - Optimized Print Speed: tips-and-tricks/optimized-print-speed.md
    - Optimized Support Settings: tips-and-tricks/optimized-support-settings.md
    - Test Settings with Small Prints: tips-and-tricks/test-settings-with-small-prints.md
    - "Printing & Materials":
      - Tips for Common Materials: tips-and-tricks/printing-&-materials/tips_for_common_materials.md
    - Slicer & Software:
      - Designing for 3D Printing: tips-and-tricks/slicer-software/designing-for-3d-printing.md

  - Downloads:
    - downloads/index.md
    - CAD Files: downloads/transferencias/cad-files.md
    - STL Files: downloads/transferencias/stl-files.md
    - BOM Files: downloads/transferencias/bom-files.md
    - Slicer Profiles: downloads/transferencias/slicer-profiles.md
    - Firmware Configuration: downloads/transferencias/firmware-configuration.md
    - Offline Manual: downloads/transferencias/offline-manual.md

  - FAQ: faq.md

  - About:
    - Overview: about/overview.md
    - Features: about/features.md
    - Specifications: about/specifications.md
    - What's in the box: about/box-contents.md
    - Warranty: about/warranty.md

